theme = "slick"
icons = "awesome5"

[[block]]
block = "memory"
display_type = "memory"
format_mem = "{mem_total_used_percents}"
format_swap = "{swap_used_percents}"

[[block]]
block = "battery"
interval = 10
format = "{percentage} {time}"

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "load"
interval = 1
format = "{1m}"

[[block]]
block = "sound"

[[block]]
block = "toggle"
text = "VPN"
command_state = "nmcli con show --active | grep -i vpn"
command_on = "nmcli con up id DeviceBits"
command_off = "nmcli con down id DeviceBits"
interval = 5

[[block]]
block = "net"
device = "wlan0"
format = "{signal_strength} {speed_down;K*b}"
interval = 5

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
